# Generated by Django 5.2 on 2025-04-24 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, spaces, and @/./+/-/_ characters.', regex='^[a-zA-Z0-9@.+-_ ]+$')]),
        ),
    ]
